"""End-to-end API workflows against the Acme CRM sample app with real Playwright executions.

Celery runs in eager mode, so discovery, generation and execution jobs execute
in-process using the same code paths as the worker.
"""

import io
import json
import zipfile

import pytest

from .conftest import make_project

pytestmark = pytest.mark.integration


def _wait_execution(api, execution):
    # Eager mode finishes the run before the create call returns.
    return api.get(f"/api/executions/{execution['id']}").json()


def test_workflow_a_website(api, sample_app):
    project = make_project(api, "Website workflow")
    r = api.post(f"/api/projects/{project['id']}/discoveries", json={"url": sample_app + "/", "authorized": False})
    assert r.status_code == 422  # authorization confirmation is mandatory
    r = api.post(f"/api/projects/{project['id']}/discoveries", json={
        "url": sample_app + "/", "authorized": True, "login_url": "/login", "username": "demo@acme.test", "password": "Passw0rd!", "max_pages": 10})
    assert r.status_code == 202, r.text
    disc = api.get(f"/api/discoveries/{r.json()['id']}").json()
    assert disc["status"] == "completed", disc
    assert disc["login_result"]["success"] is True
    assert {p["title"].split(" |")[0] for p in disc["pages"]} >= {"Dashboard", "Customers", "New customer"}
    # The sign-in page redirects once signed in, so it is not crawled; the form is recorded at sign-in.
    assert disc["login_result"]["form"]["has_password"] is True
    assert any("logout" in s["url"] for s in disc["skipped"])  # destructive links are not crawled
    assert next(p for p in disc["pages"] if p["url"].endswith("/customers"))["requires_login"] is True

    job = api.post(f"/api/discoveries/{disc['id']}/generate", json={}).json()
    job = api.get(f"/api/generation-jobs/{job['id']}").json()
    assert job["status"] == "completed" and job["result"]["created"] >= 15 and job["result"]["invalid"] == 0
    assert job["result"]["ai"]["used"] is False  # no AI key in tests: deterministic planner only, and it says so
    cases = api.get(f"/api/projects/{project['id']}/test-cases").json()
    assert all(c["status"] == "generated" for c in cases)  # generated, not executed
    assert all(c["last_result"] is None for c in cases)

    pick = [c["id"] for c in cases if c["title"] in (
        "Verify login with valid credentials", "Verify login rejects invalid credentials", 'Verify navigation to "Customers"')
        or c["category"] == "boundary"]
    assert len(pick) >= 4
    ex = api.post(f"/api/projects/{project['id']}/executions", json={"test_case_ids": pick, "workers": 2}).json()
    ex = _wait_execution(api, ex)
    assert ex["status"] == "passed", [(r["test_title"], r["error_message"]) for r in ex["results"]]
    assert ex["passed"] == len(pick)
    assert {a["name"] for a in ex["reports"]} == {"report.html", "report.pdf"}
    detail = api.get(f"/api/results/{ex['results'][0]['id']}").json()
    assert detail["generated_code"].startswith("// Generated by LorvenLax")
    assert any(a["kind"] == "screenshot" for a in detail["artifacts"])
    shot = next(a for a in detail["artifacts"] if a["kind"] == "screenshot")
    resp = api.get(shot["url"])
    assert resp.status_code == 200 and resp.content[:4] == b"\x89PNG"
    assert "Passw0rd!" not in json.dumps(detail)

    html = api.get(f"/api/executions/{ex['id']}/report?format=html")
    assert html.status_code == 200 and "LorvenLax test report" in html.text
    pdf = api.get(f"/api/executions/{ex['id']}/report?format=pdf")
    assert pdf.status_code == 200 and pdf.content[:4] == b"%PDF"
    allure = zipfile.ZipFile(io.BytesIO(api.get(f"/api/executions/{ex['id']}/report?format=allure").content))
    results = [json.loads(allure.read(n)) for n in allure.namelist() if n.endswith("-result.json")]
    assert len(results) == len(pick) and all(r["status"] == "passed" for r in results)

    dash = api.get(f"/api/organizations/{api.org_id}/dashboard").json()
    assert dash["results"]["passed"] >= len(pick) and dash["executions"] >= 1


def test_failure_analysis_and_self_healing(api, sample_app):
    project = make_project(api, "Healing", sample_app)
    case = api.post(f"/api/projects/{project['id']}/test-cases", json={"title": "Sign in form uses old button text", "steps": [
        {"action": "navigate", "value": "/login"},
        {"action": "fill", "target": {"strategy": "label", "value": "Email"}, "value": "demo@acme.test"},
        {"action": "click", "target": {"strategy": "role", "value": "button", "name": "Sign in now"}},
        {"action": "assert_url", "value": "/dashboard"},
    ]}).json()
    ex = api.post(f"/api/projects/{project['id']}/executions", json={"test_case_ids": [case["id"]], "timeout_ms": 20000}).json()
    ex = _wait_execution(api, ex)
    assert ex["status"] == "failed"
    result = api.get(f"/api/results/{ex['results'][0]['id']}").json()
    assert result["failure"]["category"] == "locator_failure"
    assert result["failed_step_index"] == 2
    assert any(a["kind"] == "dom" for a in result["artifacts"])
    suggestion = result["healing_suggestions"][0]
    assert suggestion["suggested_target"] == {"strategy": "role", "value": "button", "name": "Sign in"}
    assert suggestion["status"] == "pending"
    # The test is unchanged until a person accepts the suggestion.
    steps = api.get(f"/api/projects/{project['id']}/test-cases/{case['id']}").json()["steps"]
    assert steps[2]["target"]["name"] == "Sign in now"
    r = api.post(f"/api/healing-suggestions/{suggestion['id']}", json={"decision": "accept"})
    assert r.status_code == 200
    after = api.get(f"/api/projects/{project['id']}/test-cases/{case['id']}").json()
    assert after["steps"][2]["target"]["name"] == "Sign in" and after["steps"][2]["action"] == "click"
    assert after["steps"][3] == {**steps[3], "id": after["steps"][3]["id"]}  # assertion untouched
    logs = api.get(f"/api/organizations/{api.org_id}/audit-logs").json()
    assert any(l["action"] == "healing.accepted" for l in logs)
    # Re-running now gets further, and fails for a different, honest reason (no password entered).
    ex2 = _wait_execution(api, api.post(f"/api/projects/{project['id']}/executions", json={"test_case_ids": [case["id"]], "timeout_ms": 20000}).json())
    r2 = ex2["results"][0]
    assert r2["status"] == "failed" and r2["failure"]["category"] != "locator_failure"


def test_workflow_b_api(api, sample_app):
    project = make_project(api, "API workflow")
    r = api.post(f"/api/projects/{project['id']}/api-collections", json={"spec_url": sample_app + "/openapi.json", "api_token": "demo-token"})
    assert r.status_code == 201, r.text
    coll = r.json()
    assert coll["base_url"] == sample_app and coll["endpoint_count"] == 5
    job = api.post(f"/api/api-collections/{coll['id']}/generate", json={}).json()
    job = api.get(f"/api/generation-jobs/{job['id']}").json()
    assert job["status"] == "completed" and job["result"]["created"] >= 20
    cases = api.get(f"/api/projects/{project['id']}/test-cases?kind=api").json()
    categories = {c["category"] for c in cases}
    assert {"functional", "negative", "boundary", "security"} <= categories
    ex = _wait_execution(api, api.post(f"/api/projects/{project['id']}/executions",
                                       json={"test_case_ids": [c["id"] for c in cases], "workers": 4}).json())
    assert ex["status"] == "passed", [(r["test_title"], r["error_message"]) for r in ex["results"] if r["status"] != "passed"]
    detail = api.get(f"/api/results/{ex['results'][0]['id']}").json()
    api_att = next(a for a in detail["artifacts"] if a["kind"] == "api")
    body = api.get(api_att["url"]).json()
    assert "request" in body and "response" in body
    assert "demo-token" not in json.dumps(body)  # secrets redacted from evidence


def test_api_contract_violation_is_reported_as_failure(api, sample_app):
    """A test whose expectation contradicts the real response must fail; results are never fabricated."""
    project = make_project(api, "Contract")
    api.post(f"/api/projects/{project['id']}/api-collections", json={"spec_url": sample_app + "/openapi.json"})
    case = api.post(f"/api/projects/{project['id']}/test-cases", json={"title": "Health returns 201 (wrong on purpose)", "kind": "api", "steps": [
        {"action": "api_request", "options": {"method": "GET", "url": "{{api_base_url}}/api/health", "expect": {"status": [201]}}}]}).json()
    ex = _wait_execution(api, api.post(f"/api/projects/{project['id']}/executions", json={"test_case_ids": [case["id"]]}).json())
    assert ex["status"] == "failed"
    res = ex["results"][0]
    assert "HTTP status 200" in res["error_message"] and res["failure"]["category"] == "assertion_failure"


def test_workflow_c_natural_language(api, sample_app):
    project = make_project(api, "NL workflow")
    api.post(f"/api/projects/{project['id']}/discoveries", json={"url": sample_app + "/", "authorized": True, "max_pages": 10})
    conv = api.post(f"/api/projects/{project['id']}/assistant/conversations", json={}).json()
    text = ("Open the application, log in with valid credentials, navigate to the dashboard, create a new customer, "
            "and verify that the customer appears in the customer list.")
    msg = api.post(f"/api/assistant/conversations/{conv['id']}/messages", json={"content": text}).json()["messages"][0]
    plan = msg["payload"]
    assert plan["kind"] == "plan" and plan["engine"] == "deterministic"
    assert {p["variable"] for p in plan["prerequisites"]} == {"username", "password"}
    # Provide the missing prerequisites in the chat; the password is stored encrypted and redacted from history.
    reply = api.post(f"/api/assistant/conversations/{conv['id']}/messages",
                     json={"content": "username is demo@acme.test, password is Passw0rd!"}).json()["messages"][0]
    assert "password" in reply["payload"]["stored_variables"]
    history = api.get(f"/api/assistant/conversations/{conv['id']}").json()
    assert "Passw0rd!" not in json.dumps(history)

    # The user edits a step before saving (rename the generated description) - review is part of the flow.
    steps = plan["steps"]
    steps[-1]["description"] = "New customer is listed"
    case = api.post(f"/api/assistant/messages/{msg['id']}/save", json={"steps": steps, "title": "Create customer via NL"}).json()
    v = api.post(f"/api/projects/{project['id']}/test-cases/{case['id']}/validate").json()
    assert v["status"] in ("valid", "warnings") and v["compiled"] is True
    run = api.post(f"/api/assistant/conversations/{conv['id']}/run", json={"test_case_id": case["id"]}).json()
    ex = _wait_execution(api, run["execution"])
    assert ex["status"] == "passed", [(r["test_title"], r["error_message"]) for r in ex["results"]]
    analysis = api.post(f"/api/assistant/conversations/{conv['id']}/messages", json={"content": "why did it fail?"}).json()["messages"][0]
    assert "passed" in analysis["content"]


def test_cancelling_a_queued_execution(api):
    project = make_project(api, "Cancel", "https://example.com")
    from app.db import SessionLocal
    from app.models import TestExecution

    with SessionLocal() as db:
        ex = TestExecution(project_id=project["id"], status="queued", total=0)
        db.add(ex)
        db.commit()
        ex_id = ex.id
    r = api.post(f"/api/executions/{ex_id}/cancel")
    assert r.status_code == 200 and r.json()["status"] == "cancelled"
    assert api.post(f"/api/executions/{ex_id}/cancel").status_code == 409


def test_idempotent_execution_creation(api, sample_app):
    project = make_project(api, "Idempotent", sample_app)
    case = api.post(f"/api/projects/{project['id']}/test-cases", json={"title": "health", "kind": "api", "steps": [
        {"action": "api_request", "options": {"method": "GET", "url": sample_app + "/api/health", "expect": {"status": [200]}}}]}).json()
    body = {"test_case_ids": [case["id"]], "idempotency_key": "build-123"}
    first = api.post(f"/api/projects/{project['id']}/executions", json=body).json()
    second = api.post(f"/api/projects/{project['id']}/executions", json=body).json()
    assert first["id"] == second["id"]


def test_runtime_network_guard_blocks_internal_targets(api, sample_app):
    """URLs hidden behind variables pass static validation but are blocked by the engine at run time."""
    project = make_project(api, "Guard", sample_app)
    case = api.post(f"/api/projects/{project['id']}/test-cases", json={"title": "Reach loopback via variable", "steps": [
        {"action": "set_variable", "value": "http://127.0.0.2:9/", "options": {"name": "target"}},
        {"action": "navigate", "value": "{{target}}"},
        {"action": "assert_title", "value": "anything"},
    ]}).json()
    assert case["validation_status"] != "invalid"
    api_case = api.post(f"/api/projects/{project['id']}/test-cases", json={"title": "Metadata via variable", "kind": "api", "steps": [
        {"action": "set_variable", "value": "http://169.254.169.254", "options": {"name": "meta"}},
        {"action": "api_request", "options": {"method": "GET", "url": "{{meta}}/latest/meta-data", "expect": {"status": [200]}}},
    ]}).json()
    ex = _wait_execution(api, api.post(f"/api/projects/{project['id']}/executions",
                                       json={"test_case_ids": [case["id"], api_case["id"]], "timeout_ms": 20000}).json())
    assert ex["status"] == "failed" and ex["failed"] == 2
    for r in ex["results"]:
        assert "blocked by network policy" in r["error_message"]
        assert r["failure"]["category"] == "environment_failure"


def test_pages_that_show_login_in_place_get_login_steps(api, sample_app):
    """Single-page apps often show the sign-in form at the same URL instead of redirecting.
    Discovery must still mark such pages as requiring login, so generated tests sign in first."""
    project = make_project(api, "In-place login")
    disc = api.post(f"/api/projects/{project['id']}/discoveries", json={
        "url": sample_app + "/", "authorized": True, "login_url": "/login", "username": "demo@acme.test",
        "password": "Passw0rd!", "max_pages": 12}).json()
    disc = api.get(f"/api/discoveries/{disc['id']}").json()
    billing = next(p for p in disc["pages"] if p["url"].endswith("/billing"))
    assert billing["requires_login"] is True
    assert billing["forms"] and billing["forms"][0]["fields"][0]["label"] == "Pays *"

    job = api.get(f"/api/generation-jobs/{api.post(f'/api/discoveries/{disc['id']}/generate', json={}).json()['id']}").json()
    cases = [c for c in api.get(f"/api/projects/{project['id']}/test-cases").json()
             if c["id"] in job["result"]["test_case_ids"] and "Renew subscription" in c["title"]]
    assert cases, "expected generated tests for the billing form"
    for c in cases:
        steps = api.get(f"/api/projects/{project['id']}/test-cases/{c['id']}").json()["steps"]
        assert steps[0]["value"] == "/login" and any(s["value"] == "{{password}}" for s in steps)
    ex = _wait_execution(api, api.post(f"/api/projects/{project['id']}/executions",
                                       json={"test_case_ids": [c["id"] for c in cases]}).json())
    assert ex["status"] == "passed", [(r["test_title"], r["error_message"]) for r in ex["results"] if r["status"] != "passed"]


def test_login_steps_use_the_real_sign_in_form(api, sample_app):
    """The sign-in page redirects away once signed in, and a change-password form (several password
    fields) is found first. Login steps must still come from the real sign-in form, and the
    change-password form must never be submitted with valid data."""
    project = make_project(api, "Real login form")
    disc = api.post(f"/api/projects/{project['id']}/discoveries", json={
        "url": sample_app + "/", "authorized": True, "login_url": "/login", "username": "demo@acme.test",
        "password": "Passw0rd!", "max_pages": 15}).json()
    disc = api.get(f"/api/discoveries/{disc['id']}").json()
    assert disc["login_result"]["success"] is True
    assert any(p["url"].endswith("/account/password") for p in disc["pages"])
    job = api.get(f"/api/generation-jobs/{api.post(f'/api/discoveries/{disc['id']}/generate', json={}).json()['id']}").json()
    cases = [c for c in api.get(f"/api/projects/{project['id']}/test-cases").json() if c["id"] in job["result"]["test_case_ids"]]
    by_title = {c["title"]: c for c in cases}

    login = api.get(f"/api/projects/{project['id']}/test-cases/{by_title['Verify login with valid credentials']['id']}").json()["steps"]
    assert login[0]["value"] == "/login"
    assert [s["value"] for s in login if s["action"] == "fill"] == ["{{username}}", "{{password}}"]
    assert not any("New password" in str(s["target"]) for s in login)
    assert not any(t.startswith("Validate form submission: Change password") for t in by_title)

    ex = _wait_execution(api, api.post(f"/api/projects/{project['id']}/executions",
                                       json={"test_case_ids": [c["id"] for c in cases], "workers": 2}).json())
    assert ex["status"] == "passed", [(r["test_title"], r["error_message"][:200]) for r in ex["results"] if r["status"] != "passed"]
