"""Deterministic Playwright TypeScript generation from structured steps.

Every user- or AI-provided value is emitted through ``json.dumps``, so the
resulting code contains only calls into the LorvenLax runtime with literal
arguments. No string from a test case is ever interpreted as code.
"""

from __future__ import annotations

import json
from typing import Any, Iterable, Protocol

from .steps import ACTIONS, UI_ACTIONS


class StepLike(Protocol):
    action: str
    target: dict | None
    value: str | None
    options: dict
    description: str


def _j(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _target(target: dict | None) -> str:
    if not target:
        return "null"
    clean = {k: target[k] for k in ("strategy", "value", "name", "exact", "nth") if k in target and target[k] not in (None, "")}
    return _j(clean)


def step_call(step: StepLike) -> str:
    a, t, v, o = step.action, step.target, step.value, step.options or {}
    fixture = "llx"
    if a == "navigate":
        return f"await {fixture}.navigate({_j(v or '/')});"
    if a == "click":
        return f"await {fixture}.click({_target(t)});"
    if a == "fill":
        return f"await {fixture}.fill({_target(t)}, {_j(v or '')});"
    if a == "select":
        return f"await {fixture}.select({_target(t)}, {_j(v or '')});"
    if a in ("check", "uncheck"):
        return f"await {fixture}.{a}({_target(t)});"
    if a == "press":
        return f"await {fixture}.press({_target(t)}, {_j(v or 'Enter')});"
    if a == "wait_for":
        return f"await {fixture}.waitFor({_target(t)}, {_j(o.get('state', 'visible'))});"
    if a == "wait_ms":
        return f"await {fixture}.waitMs({int(v or 0)});"
    if a == "assert_visible":
        return f"await {fixture}.expectVisible({_target(t)});"
    if a == "assert_hidden":
        return f"await {fixture}.expectHidden({_target(t)});"
    if a == "assert_text":
        return f"await {fixture}.expectText({_target(t)}, {_j(v or '')});"
    if a == "assert_no_text":
        return f"await {fixture}.expectNoText({_j(v or '')});"
    if a == "assert_value":
        return f"await {fixture}.expectValue({_target(t)}, {_j(v or '')});"
    if a == "assert_count":
        return f"await {fixture}.expectCount({_target(t)}, {int(v or 0)});"
    if a == "assert_url":
        return f"await {fixture}.expectUrl({_j(v or '')});"
    if a == "assert_url_not":
        return f"await {fixture}.expectUrlNot({_j(v or '')});"
    if a == "assert_title":
        return f"await {fixture}.expectTitle({_j(v or '')});"
    if a == "screenshot":
        return f"await {fixture}.screenshot({_j(v or 'screenshot')});"
    if a == "store_text":
        return f"await {fixture}.storeText({_target(t)}, {_j(v or 'value')});"
    if a == "set_variable":
        return f"{fixture}.setVar({_j(o.get('name') or 'value')}, {_j(v or '')});"
    if a == "api_request":
        spec = {k: o[k] for k in ("method", "url", "headers", "query", "body", "raw_body", "expect", "store") if k in o}
        return f"await {fixture}.api({_j(spec)});"
    raise ValueError(f"Unsupported action: {a}")


def uses_browser(steps: Iterable[StepLike]) -> bool:
    return any(s.action in UI_ACTIONS for s in steps)


def generate_spec(test_id: str, title: str, steps: list[StepLike], runtime_import: str = "../runtime") -> str:
    """Return the source of one Playwright spec file for a test case."""
    fixture = "llx" if uses_browser(steps) else "llxApi"
    lines = [
        "// Generated by LorvenLax AI Testing Platform. Edit the test steps, not this file.",
        f"import {{ test }} from {_j(runtime_import)};",
        "",
        f"test({_j(f'[{test_id}] {title}')}, async ({{ {fixture}: llx }}) => {{",
    ]
    for i, step in enumerate(steps, start=1):
        label = f"Step {i}: {step.description or ACTIONS[step.action].label}"
        lines.append(f"  await test.step({_j(label)}, async () => {{")
        lines.append(f"    {step_call(step)}")
        lines.append("  });")
    lines.append("});")
    return "\n".join(lines) + "\n"
