"""Artifact storage: local filesystem (development) or S3-compatible object storage.

Keys are always generated by the platform (org/project/... prefixes), never
taken from user input, and artifacts are only served through endpoints that
check project membership first.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import BinaryIO, Iterator, Protocol

from ..config import get_settings


class Storage(Protocol):
    def put_file(self, key: str, path: Path, content_type: str) -> int: ...
    def put_bytes(self, key: str, data: bytes, content_type: str) -> int: ...
    def open(self, key: str) -> Iterator[bytes]: ...
    def read(self, key: str) -> bytes: ...
    def delete_prefix(self, prefix: str) -> None: ...


class LocalStorage:
    def __init__(self, root: Path):
        self.root = root.resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if self.root not in path.parents:
            raise ValueError("invalid storage key")
        return path

    def put_file(self, key: str, path: Path, content_type: str) -> int:
        dest = self._path(key)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(path, dest)
        return dest.stat().st_size

    def put_bytes(self, key: str, data: bytes, content_type: str) -> int:
        dest = self._path(key)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
        return len(data)

    def open(self, key: str) -> Iterator[bytes]:
        with self._path(key).open("rb") as fh:
            while chunk := fh.read(64 * 1024):
                yield chunk

    def read(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def delete_prefix(self, prefix: str) -> None:
        shutil.rmtree(self._path(prefix), ignore_errors=True)


class S3Storage:
    def __init__(self):
        import boto3

        s = get_settings()
        self.bucket = s.s3_bucket
        self.client = boto3.client(
            "s3",
            endpoint_url=s.s3_endpoint_url or None,
            aws_access_key_id=s.s3_access_key or None,
            aws_secret_access_key=s.s3_secret_key or None,
            region_name=s.s3_region,
        )
        try:
            self.client.head_bucket(Bucket=self.bucket)
        except Exception:  # noqa: BLE001
            self.client.create_bucket(Bucket=self.bucket)

    def put_file(self, key: str, path: Path, content_type: str) -> int:
        self.client.upload_file(str(path), self.bucket, key, ExtraArgs={"ContentType": content_type})
        return path.stat().st_size

    def put_bytes(self, key: str, data: bytes, content_type: str) -> int:
        self.client.put_object(Bucket=self.bucket, Key=key, Body=data, ContentType=content_type)
        return len(data)

    def open(self, key: str) -> Iterator[bytes]:
        body: BinaryIO = self.client.get_object(Bucket=self.bucket, Key=key)["Body"]
        while chunk := body.read(64 * 1024):
            yield chunk

    def read(self, key: str) -> bytes:
        return self.client.get_object(Bucket=self.bucket, Key=key)["Body"].read()

    def delete_prefix(self, prefix: str) -> None:
        paginator = self.client.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=self.bucket, Prefix=prefix):
            keys = [{"Key": o["Key"]} for o in page.get("Contents", [])]
            if keys:
                self.client.delete_objects(Bucket=self.bucket, Delete={"Objects": keys})


_storage: Storage | None = None


def get_storage() -> Storage:
    global _storage
    if _storage is None:
        s = get_settings()
        _storage = S3Storage() if s.storage_backend == "s3" else LocalStorage(s.storage_local_root)
    return _storage
